DROP DATABASE IF EXISTS tilewars;
CREATE DATABASE tilewars;
\c tilewars
CREATE TABLE board (
	x INT NOT NULL,
	y INT NOT NULL,
	color VARCHAR(15)
);
CREATE TABLE messages (
	name TEXT NOT NULL,
	text TEXT NOT NULL,
	color VARCHAR(15) DEFAULT 'gray',
	timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE players (
	id TEXT NOT NULL,
	color VARCHAR(15),
	x INT NOT NULL,
	y INT NOT NULL,
	alive BOOLEAN DEFAULT TRUE
);